# Generated by Django 2.2.16 on 2020-11-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.TextField(default='n/a')),
                ('password', models.TextField(default='N/A')),
            ],
        ),
    ]
